security:
    firewalls:
        secured_area:
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check            
            http_basic:
                realm: "Area demo protetta"

    access_control:
        - { path: ^/nuovo_blog, roles: ROLE_ADMIN }

    providers:
        in_memory:
            users:
                enrico: { password: tempe08, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
