# src/Enrico/BlogBundle/Resources/config/routing.yml
EnricoBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: EnricoBlogBundle:Page:index }
    requirements:
        _method:  GET
        
EnricoBlogBundle_about:
    pattern:  /about
    defaults: { _controller: EnricoBlogBundle:Page:about }
    requirements:
        _method:  GET
        
EnricoBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: EnricoBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

        
