parameters:
#    enrico_blog.example.class: Enrico\BlogBundle\Example

services:
#    enrico_blog.example:
#        class: %enrico_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
